language: java
jdk:
  - openjdk8

branches:
  only:
    - master

# Travis CI 서버의 Home
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script:
  - "./gradlew clean build"

before_deploy:
  - zip -r aws-jpa-springboot
  - mkdir -p deploy
  - mv aws-jpa-springboot.zip deploy/aws-jpa-springboot.zip

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY # Travis repo settings에 설정된 값
    secret_access_key: $AWS_SECRET_KEY # Travis repo settings에 설정된 값
    bucket: aws-spring-build # S3 버킷
    region: us-east-1
    skip_cleanup: true
    acl: public_read_write # zip 파일 접근을 private으로
    local_dir: deploy # before_deploy에서 생성한 디렉토리
    wait-until-deployed: true

# CI 실행 완료시 메일로 알람!
notifications:
  email:
    recipients:
      - hanovator@gmail.com